export const queryKeys = {
  auth: ['auth', 'me'] as const,
  dashboard: ['dashboard'] as const,
  activity: (type: string, page: number) => ['activity', type, page] as const,
  mealPlans: (filters?: unknown) => ['meal-plans', filters] as const,
  mealPlan: (id: string) => ['meal-plan', id] as const,
  shoppingLists: (filters?: unknown) => ['shopping-lists', filters] as const,
  shoppingList: (id: string) => ['shopping-list', id] as const,
  catalogSyncOverview: ['admin', 'catalog-sync', 'overview'] as const,
  catalogSyncRuns: (filters: unknown) => ['admin', 'catalog-sync', 'runs', filters] as const,
  catalogSyncErrors: (id: string) => ['admin', 'catalog-sync', 'errors', id] as const,
  nutritionOverview: ['admin', 'nutrition', 'overview'] as const,
  nutritionRuns: (page: number) => ['admin', 'nutrition', 'runs', page] as const,
  nutritionCandidates: (page: number) => ['admin', 'nutrition', 'candidates', page] as const,
}
