import type { MealTemplate, Product } from '../types/api'

export const productFixture: Product = {
  id: '10000000-0000-4000-8000-000000000001',
  supermarketCode: 'MERCADONA',
  supermarketName: 'Mercadona',
  categoryId: '20000000-0000-0000-0000-000000000001',
  categoryName: 'Cereales y pasta',
  externalId: 'demo-rice',
  barcode: 'DEMO-1',
  name: 'Arroz largo',
  brand: 'Despensa demo',
  description: 'Producto ficticio',
  imageUrl: null,
  currentPrice: 1.45,
  unitPrice: 1.45,
  packageQuantity: 1,
  packageUnit: 'KG',
  measurementType: 'WEIGHT',
  costDataComplete: true,
  available: true,
  source: 'DEMO_JSON',
  lastSyncedAt: '2026-07-28T00:00:00Z',
  nutrition: {
    caloriesPer100g: 354,
    proteinPer100g: 7.2,
    carbohydratesPer100g: 78,
    fatPer100g: 0.8,
    fiberPer100g: 1.3,
    sugarPer100g: 0.2,
    saltPer100g: 0.01,
    saturatedFatPer100g: null,
    nutritionBasis: 'PER_100_GRAMS',
    completeness: 'COMPLETE',
    sourceReference: null,
    sourceUpdatedAt: null,
    perUnit: null,
    dataSource: 'CONTROLLED_DEMO_DATA',
    verificationStatus: 'DEMO',
    confidenceScore: 1,
    updatedAt: '2026-07-28T00:00:00Z',
  },
  dietaryTags: [],
  allergens: [],
  demonstrationData: true,
}

export const mealTemplateFixture: MealTemplate = {
  id: '40000000-0000-4000-8000-000000000001',
  supermarketCode: 'MERCADONA',
  supermarketName: 'Mercadona',
  name: 'Arroz con pollo y espinacas',
  description: 'Comida sencilla y alta en proteína',
  mealType: 'LUNCH',
  instructions: ['Cocer el arroz.', 'Cocinar el pollo.', 'Mezclar y servir.'],
  preparationMinutes: 25,
  servings: 2,
  active: true,
  imageUrl: null,
  ingredients: [
    {
      productId: productFixture.id,
      productName: productFixture.name,
      brand: productFixture.brand,
      category: productFixture.categoryName,
      quantity: 160,
      quantityUnit: 'GRAM',
      optional: false,
      sortOrder: 0,
      notes: 'Peso en seco',
      calculatedNutrition: {
        calories: 566.4,
        protein: 11.5,
        carbohydrates: 124.8,
        fat: 1.3,
        fiber: 2.1,
        sugar: 0.3,
        salt: 0,
      },
      calculatedConsumedCost: 0.23,
      nutritionCalculationComplete: true,
      costCalculationComplete: true,
      calculationComplete: true,
      warnings: [],
    },
  ],
  totalNutrition: {
    calories: 900,
    protein: 70,
    carbohydrates: 125,
    fat: 8,
    fiber: 4,
    sugar: 1,
    salt: 0.6,
  },
  nutritionPerServing: {
    calories: 450,
    protein: 35,
    carbohydrates: 62.5,
    fat: 4,
    fiber: 2,
    sugar: 0.5,
    salt: 0.3,
  },
  totalConsumedCost: 3.5,
  consumedCostPerServing: 1.75,
  calculationComplete: true,
  nutritionComplete: true,
  costComplete: true,
  warnings: [],
  createdAt: '2026-07-28T00:00:00Z',
  updatedAt: '2026-07-28T00:00:00Z',
  demoData: true,
}

export const partialMealTemplateFixture: MealTemplate = {
  ...mealTemplateFixture,
  id: '40000000-0000-4000-8000-000000000002',
  name: 'Hamburguesa vegetal con tomate',
  active: false,
  calculationComplete: false,
  nutritionComplete: false,
  costComplete: false,
  warnings: [
    'No hay información nutricional para Hamburguesa vegetal.',
    'El coste no se puede calcular para Hamburguesa vegetal.',
  ],
  ingredients: [
    {
      ...mealTemplateFixture.ingredients[0]!,
      productId: '10000000-0000-4000-8000-000000000002',
      productName: 'Hamburguesa vegetal',
      calculatedNutrition: null,
      calculatedConsumedCost: null,
      nutritionCalculationComplete: false,
      costCalculationComplete: false,
      calculationComplete: false,
      warnings: ['No hay información nutricional para Hamburguesa vegetal.'],
    },
  ],
}

export const supermarketsFixture = [
  {
    code: 'MERCADONA',
    name: 'Mercadona',
    enabled: true,
    catalogSource: 'DEMO_JSON',
    countryCode: 'ES',
    currencyCode: 'EUR',
  },
  {
    code: 'CARREFOUR',
    name: 'Carrefour',
    enabled: false,
    catalogSource: 'PLANNED',
    countryCode: 'ES',
    currencyCode: 'EUR',
  },
]

export function mealTemplatePage(content = [mealTemplateFixture, partialMealTemplateFixture]) {
  return {
    content,
    page: 0,
    size: 9,
    totalElements: content.length,
    totalPages: content.length ? 1 : 0,
    first: true,
    last: true,
  }
}
