import type { GeneratedMealPlan, MealPlanSummary } from '../types/mealPlan'

const nutrition = {
  calories: 500,
  protein: 35,
  carbohydrates: 60,
  fat: 12,
  fiber: 7,
  sugar: 5,
  salt: 0.8,
}

export const generatedMealPlanFixture: GeneratedMealPlan = {
  persisted: false,
  mealPlanId: null,
  generationToken: 'a'.repeat(64),
  name: 'Plan semanal demo',
  supermarketCode: 'MERCADONA',
  supermarketName: 'Mercadona',
  startDate: '2026-08-03',
  numberOfDays: 1,
  mealsPerDay: 1,
  servings: 1,
  seed: 123456,
  strategy: 'SCORING',
  status: 'DRAFT',
  criteria: {
    dailyCaloriesTarget: 2000,
    dailyProteinTarget: 100,
    allowedMealTypes: ['LUNCH'],
    requiredDietaryTags: [],
    excludedAllergens: [],
    excludedTemplateIds: [],
    excludedProductIds: [],
    maximumPreparationMinutes: 40,
    maximumTemplateRepetitions: 3,
    varietyPreference: 'HIGH',
    allowIncompleteCalculations: false,
  },
  days: [
    {
      dayIndex: 0,
      date: '2026-08-03',
      meals: [
        {
          position: 0,
          mealType: 'LUNCH',
          templateId: '40000000-0000-4000-8000-000000000001',
          templateName: 'Arroz con pollo',
          servings: 1,
          preparationMinutes: 25,
          ingredients: [
            {
              productId: '10000000-0000-4000-8000-000000000001',
              productName: 'Arroz largo',
              quantity: 80,
              quantityUnit: 'GRAM',
            },
          ],
          nutrition,
          consumedCost: 1.8,
          score: 82,
          calculationComplete: true,
          warnings: [],
        },
      ],
      totalNutrition: nutrition,
      totalConsumedCost: 1.8,
      calorieTarget: 2000,
      proteinTarget: 100,
      calorieDeviation: 1500,
      calorieDeviationPercentage: 75,
      proteinDeviation: -65,
      dailyScore: 20,
      warnings: [],
    },
  ],
  weeklyNutrition: nutrition,
  totalConsumedCost: 1.8,
  weeklyBudget: 70,
  budgetDifference: 68.2,
  budgetExceeded: false,
  budgetDeviationPercentage: 97.4,
  overallScore: 62.5,
  scoreBreakdown: {
    calorieScore: 20,
    proteinScore: 35,
    budgetScore: 100,
    varietyScore: 100,
    repetitionScore: 100,
    completenessScore: 100,
    preparationScore: 88,
    totalScore: 62.5,
  },
  varietyMetrics: {
    uniqueTemplates: 1,
    repeatedTemplates: 0,
    maximumObservedRepetition: 1,
    varietyScore: 100,
  },
  calculationComplete: true,
  warnings: [
    {
      code: 'CONSUMED_COST_ONLY',
      message: 'El presupuesto usa coste consumido',
      severity: 'INFO',
      dayIndex: null,
    },
  ],
  constraintsApplied: ['Supermarket: MERCADONA'],
  constraintsNotMet: ['Daily calorie target outside margin'],
  rejectedCandidateStatistics: { unavailableProduct: 2 },
  generationMetadata: {
    strategy: 'SCORING',
    seed: 123456,
    durationMilliseconds: 120,
    candidatesEvaluated: 50,
    completePlansEvaluated: 8,
    generatedAt: '2026-07-28T10:00:00Z',
    algorithmVersion: 'scoring-beam-v1',
    beamWidth: 24,
    candidatesPerPosition: 8,
  },
  createdAt: null,
  updatedAt: null,
}

export const purchaseAwareMealPlanFixture: GeneratedMealPlan = {
  ...generatedMealPlanFixture,
  strategy: 'PURCHASE_AWARE_SCORING',
  purchaseMetrics: {
    estimatedConsumedCost: 37.53,
    estimatedPurchaseCost: 53.35,
    estimatedWasteCost: 15.82,
    estimatedWastePercentage: 29.7,
    estimatedPackageCount: 25,
    estimatedUniqueProductCount: 13,
    reusedProductCount: 10,
    economicallyUsefulReuseCount: 8,
    purchaseBudgetDifference: 16.65,
    purchaseBudgetExceeded: false,
    purchaseBudgetDeviationPercentage: 23.8,
    calculationComplete: true,
    warnings: [],
    selectionReasons: [
      'Reutiliza ingredientes cuando evita envases o aprovecha sobrantes',
      'El coste estimado de compra entra en el presupuesto',
    ],
  },
  scoreBreakdown: {
    ...generatedMealPlanFixture.scoreBreakdown,
    purchaseCostScore: 73.3,
    consumedCostScore: 89.3,
    purchaseBudgetScore: 100,
    wasteCostScore: 77.4,
    wastePercentageScore: 70.3,
    usefulReuseScore: 80,
    uniqueProductsScore: 48,
    packageCountScore: 50,
    totalScore: 78.4,
  },
  overallScore: 78.4,
  generationMetadata: {
    ...generatedMealPlanFixture.generationMetadata,
    strategy: 'PURCHASE_AWARE_SCORING',
    algorithmVersion: 'purchase-aware-beam-v1',
    optimizationPreset: 'BALANCED',
    scoreWeights: {
      calories: 22,
      protein: 22,
      purchaseCost: 10,
      budget: 15,
    },
  },
}

export const mealPlanSummaryFixture: MealPlanSummary = {
  id: '50000000-0000-4000-8000-000000000001',
  name: generatedMealPlanFixture.name,
  supermarketCode: 'MERCADONA',
  supermarketName: 'Mercadona',
  startDate: '2026-08-03',
  numberOfDays: 7,
  mealsPerDay: 4,
  servings: 1,
  dailyCaloriesTarget: 2000,
  dailyProteinTarget: 100,
  totalConsumedCost: 38.5,
  weeklyBudget: 70,
  overallScore: 62.5,
  status: 'GENERATED',
  calculationComplete: true,
  warningCount: 3,
  seed: 123456,
  createdAt: '2026-07-28T10:00:00Z',
  updatedAt: '2026-07-28T10:00:00Z',
}
