import type { ShoppingList, ShoppingListSummary } from '../types/shoppingList'

export const shoppingListFixture: ShoppingList = {
  id: '70000000-0000-0000-0000-000000000001',
  mealPlanId: '60000000-0000-0000-0000-000000000001',
  mealPlanName: 'Plan semanal demo',
  supermarket: {
    id: '10000000-0000-0000-0000-000000000001',
    code: 'MERCADONA',
    name: 'Mercadona',
    currencyCode: 'EUR',
  },
  status: 'GENERATED',
  generatedAt: '2026-08-03T10:00:00Z',
  updatedAt: '2026-08-03T10:00:00Z',
  groups: [
    {
      categoryId: '20000000-0000-0000-0000-000000000001',
      categoryName: 'Carnes',
      subtotalPurchaseCost: 12,
      subtotalConsumedCost: 9.6,
      subtotalWasteCost: 2.4,
      calculationComplete: true,
      items: [
        {
          id: '71000000-0000-0000-0000-000000000001',
          productId: '30000000-0000-0000-0000-000000000001',
          productName: 'Pechuga de pollo',
          brand: 'Marca neutra',
          categoryId: '20000000-0000-0000-0000-000000000001',
          categoryName: 'Carnes',
          measurementType: 'WEIGHT',
          requiredQuantity: 1200,
          requiredUnit: 'GRAM',
          packageQuantity: 500,
          packageUnit: 'G',
          packagePrice: 4,
          unitPrice: 8,
          packagesRequired: 3,
          purchasedQuantity: 1500,
          leftoverQuantity: 300,
          consumedCost: 9.6,
          purchaseCost: 12,
          wasteCost: 2.4,
          leftoverPercentage: 20,
          available: true,
          calculationComplete: true,
          sortOrder: 0,
          warnings: [],
        },
      ],
    },
    {
      categoryId: null,
      categoryName: 'Sin categoría',
      subtotalPurchaseCost: 0,
      subtotalConsumedCost: 0,
      subtotalWasteCost: 0,
      calculationComplete: false,
      items: [
        {
          id: '71000000-0000-0000-0000-000000000002',
          productId: '30000000-0000-0000-0000-000000000002',
          productName: 'Producto antiguo',
          brand: null,
          categoryId: null,
          categoryName: null,
          measurementType: null,
          requiredQuantity: 250,
          requiredUnit: 'GRAM',
          packageQuantity: null,
          packageUnit: null,
          packagePrice: null,
          unitPrice: null,
          packagesRequired: null,
          purchasedQuantity: null,
          leftoverQuantity: null,
          consumedCost: null,
          purchaseCost: null,
          wasteCost: null,
          leftoverPercentage: null,
          available: false,
          calculationComplete: false,
          sortOrder: 1,
          warnings: ['PRODUCT_SNAPSHOT_INCOMPLETE: Package calculation is unavailable'],
        },
      ],
    },
  ],
  itemCount: 2,
  totalPackages: 3,
  totalConsumedCost: 9.6,
  totalPurchaseCost: 12,
  totalWasteCost: 2.4,
  overallWastePercentage: 20,
  quantitySummary: {
    WEIGHT: {
      required: 1200,
      purchased: 1500,
      leftover: 300,
      unit: 'GRAM',
      calculationComplete: true,
    },
    VOLUME: {
      required: 0,
      purchased: 0,
      leftover: 0,
      unit: 'MILLILITER',
      calculationComplete: true,
    },
    UNIT: {
      required: 0,
      purchased: 0,
      leftover: 0,
      unit: 'UNIT',
      calculationComplete: true,
    },
  },
  weeklyBudget: 10,
  purchaseBudgetDifference: -2,
  purchaseBudgetExceeded: true,
  purchaseBudgetDeviationPercentage: 20,
  budgetCalculationComplete: false,
  calculationComplete: false,
  warnings: [
    {
      code: 'PRODUCT_UNAVAILABLE',
      message: 'Product was unavailable',
      severity: 'WARNING',
      itemId: '71000000-0000-0000-0000-000000000002',
    },
  ],
  demoData: true,
  generationDurationMilliseconds: 12,
}

export const shoppingListSummaryFixture: ShoppingListSummary = {
  id: shoppingListFixture.id,
  mealPlanId: shoppingListFixture.mealPlanId,
  mealPlanName: shoppingListFixture.mealPlanName,
  supermarketCode: 'MERCADONA',
  supermarketName: 'Mercadona',
  status: 'GENERATED',
  generatedAt: shoppingListFixture.generatedAt,
  itemCount: 2,
  totalPackages: 3,
  totalConsumedCost: 9.6,
  totalPurchaseCost: 12,
  totalWasteCost: 2.4,
  overallWastePercentage: 20,
  weeklyBudget: 10,
  purchaseBudgetExceeded: true,
  budgetCalculationComplete: false,
  calculationComplete: false,
  warningCount: 1,
  demoData: true,
}
